version: '3'
volumes:
  jenkins-data:
  jenkins-log:
  portainer-data:
  nginx-data:
  mysql-data:
  nexus-data:

networks:
  stack-net:

services:
  jenkins:
    build: ./jenkins-master
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stack-net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - stack-net
    volumes:
      - nginx-data:/etc/nginx/conf.d
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - stack-net
    volumes:
      - mysql-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - stack-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  nexus:
    image: sonatype/nexus3:3.20.0
    networks:
      - stack-net
    volumes:
      - nexus-data:/nexus-data
    environment:
      - MAX_HEAP=1200m
      - MIN_HEAP=500m
    ports:
      - "8081:8081"
      - "8122:8122"
      - "8123:8123"

